#!/bin/bash

# https://yoshiori.hatenablog.com/entry/2021/04/13/171405
AIR_PODS_ADDRESS=3c-4d-be-12-2f-2f #3c-4d-be-12-2f-2f Your AirPods MAC address
AIR_PODS_NAME="MasahiroのAirPods Pro" # Your AirPods name

bluetoothconnector -c $AIR_PODS_ADDRESS
for ((i=0 ; i<10 ; i++))
do
    if [ "Connected" == $(bluetoothconnector  -s $AIR_PODS_ADDRESS) ]; then
        sleep 1
        SwitchAudioSource -s  "${AIR_PODS_NAME}" && say -v samantha Connected && break
    fi
    sleep 1
done
