#!/bin/bash

wget -q --spider http://google.com

if [ $? -eq 0 ]; then
    echo "Online, exit"
    exit
fi

SSID=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | awk -F ' SSID: ' '/ SSID:/ {print $2}'`
if [ 'at_STARBUCKS_Wi2' = $SSID ]; then
  open "https://service.wi2.ne.jp/freewifi/starbucks/index.html"
fi
